spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: 1208


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false